export { default as About } from "./About"
export { default as Landing } from "./Landing"
export { default as Projects } from "./Projects"
export { default as Experience } from "./Experience"
export { default as Navbar } from "./Navbar"
export { default as Contact } from "./Contact"
